### ISSUE TITLE
install tn generate error

### ISSUE THREAD

**Issue by flo-bk** [FokkeZB/tn#37]
Hello,
On mac, node v0.12.2 titanium cli 3.4.2
When i install tn i have an error:

/usr/local/bin/tn -> /usr/local/lib/node_modules/tn/bin/cli.js

> tn@2.2.3 postinstall /usr/local/lib/node_modules/tn
> node bin/cli.js install

TiNy, version 2.2.3
Copyright (c) 2013-2014, Fokke Zandbergen.  All Rights Reserved.

[INFO]  Installing Titanium CLI hook..
child_process.js:968
    throw new TypeError('options argument must be an object');
          ^
TypeError: options argument must be an object
    at normalizeSpawnArguments (child_process.js:968:11)
    at Object.exports.spawn (child_process.js:991:38)
    at spawn (/usr/local/lib/node_modules/tn/lib/setup.js:160:36)
    at Object.install (/usr/local/lib/node_modules/tn/lib/setup.js:18:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/tn/bin/cli.js:82:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "tn" "--unsafe-perm"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE

npm ERR! tn@2.2.3 postinstall: `node bin/cli.js install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tn@2.2.3 postinstall script 'node bin/cli.js install'.
npm ERR! This is most likely a problem with the tn package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/cli.js install
npm ERR! You can get their info via:
npm ERR!     npm owner ls tn
npm ERR! There is likely additional logging output above.

> tn@2.2.3 preuninstall /usr/local/lib/node_modules/tn
> node bin/cli.js uninstall

TiNy, version 2.2.3
Copyright (c) 2013-2014, Fokke Zandbergen.  All Rights Reserved.

[INFO]  Uninstalling Titanium CLI hook..
paths.hooks saved

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/MacintoshHD2/MobileCanalTP/NMPAppMobile/npm-debug.log

Thx

**Comment by FokkeZB** [comment]
Could you try to install from master?

```
npm install -g fokkezb/tn --unsafe-perm
```
