### ISSUE TITLE
Allow pre/post recipe commands

### ISSUE THREAD

**Issue by brentonhouse** [FokkeZB/tn#42]
Not sure how this could be setup yet.  Still working through a few different strategies.

Basically, I need to be able to run some to *always* run some other commands before I use certain recipes.  (i.e. ti clean, npm install, etc)
It would be nice to be able to define pre-command(s) that I could include in a recipe that would execute before executing the primary recipe.

**Comment by FokkeZB** [comment]
I think it's better to use bash aliases or Grunt/Gulp or even just NPM run scripts for those cases. I don't want to turn TiNy into a generic CLI wrapper.

**Comment by brentonhouse** [comment]
gotcha
