### ISSUE TITLE
Install Error. Not sure what is going on here.

### ISSUE THREAD

**Issue by gstreetmedia** [FokkeZB/tn#43]
Andys-iMac:~ andy$ sudo npm install -g tn --unsafe-perm
Password:
/usr/local/bin/tn -> /usr/local/lib/node_modules/tn/bin/cli.js

> tn@3.0.3 postinstall /usr/local/lib/node_modules/tn
> node bin/cli.js uninstall

TiNy, version 3.0.3
Copyright (c) 2013-2015, Fokke Zandbergen.  All Rights Reserved.

[INFO]  Uninstalling the old 2.x Titanium CLI hook..
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn ti ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "tn" "--unsafe-perm"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! tn@3.0.3 postinstall: `node bin/cli.js uninstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tn@3.0.3 postinstall script 'node bin/cli.js uninstall'.
npm ERR! This is most likely a problem with the tn package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/cli.js uninstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls tn
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andy/npm-debug.log
Andys-iMac:~ andy$

**Comment by FokkeZB** [comment]
I've fixed this in the new version 4.0
