### ISSUE TITLE
tn doesn't actually execute appc

### ISSUE THREAD

**Issue by iotashan** [FokkeZB/tn#44]
tn detected the project as a platform project, and even displayed that the cooked command was an "appc" one, but then executed with ti instead:

```
MacBook-Pro: shan$ tn nexus-7
TiNy cooked: appc ti build --platform android --target device --device-id 0583a2a0

Titanium Command-Line Interface, CLI version 4.0.1, Titanium SDK version 4.0.0.GA
```

Yes, appc is installed. Copying & pasting the cooked command works as expected:

```
MacBook-Pro: shan$ appc ti build --platform android --target device --device-id 0583a2a0
Appcelerator Command-Line Interface, version 4.1.2
```

**Comment by iotashan** [comment]
Oops, forgot the key details: `TiNy, version 4.0.2`

OS X 10.5.5

**Comment by FokkeZB** [comment]
That's weird, can't reproduce this. Can you `sudo npm install -g appc-compat` and run `appc-compat ti info` to see what that gives you?

**Comment by iotashan** [comment]
```
MacBook-Pro:~ shan$ appc-compat ti info
Titanium Command-Line Interface, CLI version 4.0.1, Titanium SDK version 4.0.0.GA
```

**Comment by FokkeZB** [comment]
Sorry, I mean `appc-compat ti info --prefer-appc`

**Comment by iotashan** [comment]
```
MacBook-Pro:~ shan$ appc-compat ti info --prefer-appc
Appcelerator Command-Line Interface, version 4.1.2
Copyright (c) 2014-2015, Appcelerator, Inc.  All Rights Reserved.
```

**Comment by FokkeZB** [comment]
mm, so that does work. Then why on earth does it not work when TiNy uses the exact same lib?! Can you do some digging around in the code in your node_modules folder to see if you get anywhere?

**Comment by iotashan** [comment]
Found the problem: https://github.com/FokkeZB/tn/blob/master/bin/cli.js#L134-L135

preferAppc is an opt (second param) not an arg (first param) in the appc-compat library.

fugly hack:
```
    var eat = function () {
      compat.ti(args, {
        stdio: 'inherit',
        preferAppc: args.preferAppc
      });
    };
```

**Comment by FokkeZB** [comment]
Thanks!
