### ISSUE TITLE
use run instead build?

### ISSUE THREAD

**Issue by DouglasHennrich** [FokkeZB/tn#48]
There's a way to use `appc run` instead `ti build` ?

Thanks

**Comment by FokkeZB** [comment]
If TiNy finds an `appc-app-id` element in your `tiapp.xml` it will use `appc run`, you can also force this using the `--prefer-appc` flag.

https://github.com/FokkeZB/tn/blob/2d836ba36d3194bd2a843d37cb60eb980938d03d/bin/cli.js#L128
